version: "3"

services:
    server:
        image: dockable/nginx
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/usr/share/nginx/html
            - ./site.conf:/etc/nginx/conf.d/site.conf
    database:
        image: mongo:3.7.1-jessie
        ports:
            - 27017:27017
        volumes:
            - ./data/:/data/db
