version: "3"

services:
    webserver:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        image: dockable/nginx
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/html
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        image: dockable/php
        volumes:
            - ./:/usr/share/nginx/html
    database:
        image: mongo:3.7.1-jessie
